"""Public contracts for the Universal Data Plane."""

from openjarvis.data_plane.errors import DataPlaneError, DataPlaneErrorCode
from openjarvis.data_plane.types import (
    ConsistencyMode,
    DiscoveryConstraints,
    DiscoveryEvidence,
    DiscoveryResult,
    ExecutionReceipt,
    MatchResult,
    NormalizedBatch,
    OperationContract,
    OperationName,
    ReceiptId,
    ReceiptStatus,
    ResourceRecord,
    ResourceRef,
    ResourceType,
    SnapshotCommit,
    SnapshotDiff,
    SnapshotRef,
    SourceCapability,
    SourceId,
    SourceRef,
    StructuredQuery,
    StructuredResult,
    StructuredSnapshot,
    StructuredSourceAdapter,
    SyncReceipt,
    TransportKind,
    TrustState,
    VerificationResult,
)

__all__ = [
    "ConsistencyMode",
    "DataPlaneError",
    "DataPlaneErrorCode",
    "DiscoveryConstraints",
    "DiscoveryEvidence",
    "DiscoveryResult",
    "ExecutionReceipt",
    "MatchResult",
    "NormalizedBatch",
    "OperationContract",
    "OperationName",
    "ReceiptId",
    "ReceiptStatus",
    "ResourceRecord",
    "ResourceRef",
    "ResourceType",
    "SnapshotCommit",
    "SnapshotDiff",
    "SnapshotRef",
    "SourceCapability",
    "SourceId",
    "SourceRef",
    "StructuredQuery",
    "StructuredResult",
    "StructuredSnapshot",
    "StructuredSourceAdapter",
    "SyncReceipt",
    "TransportKind",
    "TrustState",
    "VerificationResult",
]
